### ISSUE TITLE
HAROID 부품무게가 20g에 육박

### ISSUE THREAD

**Issue by bigzero** [bigzero/HAROID#2]
부품무게가 20g에 육박해 풍선크기를 늘리던가 부품무게를 줄여야 함.

**Comment by kimdh** [comment]
16인치 헬륨풍선이 들어올릴 수 있는 무게측정 필요.

**Comment by bigzero** [comment]
12인치 풍선은 의미없음.
16인치와 그 이상의 풍선으로 준비해야할것 같음.

**Comment by bigzero** [comment]
http://m.instructables.com/id/Sub-Micro-Blimp/step2/Determining-the-weight-and-choosing-the-balloon/

16인치 풍선이 20g까지 들수 있는것 같음. 확인필요.

**Comment by bigzero** [comment]
36인치풍선이 들수 있는 무게 측정 필요
풍선모양부터 선정
