### ISSUE TITLE
풍선에 회로를 어떻게 고정할것인가?

### ISSUE THREAD

**Issue by bigzero** [bigzero/HAROID#5]
사고를 깨는 혁신이 필요함.
혁신은 다음과 같은 요건을 충족해야한다.
무게:20g 미만이 되도록.
모양: 배터리 탈부착 및 기구 탈부착 용이

 예로 배터리와 기구를 고정하기 위해 종이를 사용해도 됨. 종이 받침대를 만들어 사용.

**Comment by kimdh** [comment]
배터리에서 발생하는 열로 풍선이 터지는 사태가 발생하지 않도록 해야함.

**Comment by bigzero** [comment]
무서움
